# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Run all tests'
  lane :test do
    test_objc
    test_uikit
    test_swiftui
  end

  desc 'Run test in Objective-C project'
  lane :test_objc do
    scan(
      project: "Objective-C/EntrypointSample-ObjC.xcodeproj", 
      scheme: "EntrypointSample-ObjC"
    )
  end

  desc 'Run test in UIKit(Swift) project'
  lane :test_uikit do
    scan(
      project: "Swift-UIKit/EntrypointSample-Swift-UIKit.xcodeproj", 
      scheme: "EntrypointSample-Swift-UIKit"
    )
  end

  desc 'Run test in SwiftUI project'
  lane :test_swiftui do
    scan(
      project: "SwiftUI/EntrypointSample-SwiftUI.xcodeproj", 
      scheme: "EntrypointSample-SwiftUI"
    )
  end
end
